# Setup
title:               "Maverick's Quest"
tagline:             "Writing by Mikhail's Turilin"
description:         'Description will go here'
url:                 https://maverick.quest
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Mikhail Turilin
  url:               https://maverick.quest
  email:             mikhail@turilin.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
